"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const middlewares_1 = require("../middlewares");
const pointTransaction_validation_1 = require("../validations/pointTransaction.validation");
const pointTransaction_1 = require("../controllers/pointTransaction");
const pointTransaction_validation_2 = require("../validations/pointTransaction.validation");
const PointTransactionRoute = (0, express_1.Router)();
PointTransactionRoute.get('/', middlewares_1.MiddleWares.useAuthorization, middlewares_1.MiddleWares.validate({ query: pointTransaction_validation_1.listPointTransactionsQuerySchema }), pointTransaction_1.PointTransactionController.listPointTransactions);
PointTransactionRoute.post('/', middlewares_1.MiddleWares.useTokenAuthorization, middlewares_1.MiddleWares.validate({ body: pointTransaction_validation_2.createPointTransactionSchema }), pointTransaction_1.PointTransactionController.createPointTransaction);
exports.default = PointTransactionRoute;
